### PR TITLE
Issue #164

### LINKED ISSUE #164: After upgrading from cfn-lint 1.6.0 to 1.7.0, getting Error: Could not determine file type.
After upgrading from cfn-lint 1.6.0/1.6.2 to 1.7.0, getting `Error: Could not determine file type` for 3 of my 10 files -- all the rest validate.  Not only that, no changes were made to any of the files before and after upgrade.

All my files are valid YML CloudFormation and also pass CloudFormation validation -
 * When I run `file *` all 10/10 files are "ASCII text" - no variations in binary/ASCII/Unicode/UTF-8/etc.

 * This works for all 10/10 files:
 $ `aws cloudformation validate-template --template-url https://s3.amazonaws.com/MyS3Bucket/MyCFStack.yml`

 * While this now fails in 1.7.0, for 3/10 files but worked before in 1.6.0/1.6.2 for all 10/10:
 $ `cfn-lint --verbose --pseudo AWS::AccountId="000000000000",AWS::Region="us-east-1" validate /path/to/MyCFStack.yml`
```Unable to parse template! Use --verbose for more information.
Error: Could not determine file type. Check your template is not malformed. data.split is not a function
    at Object.openFile (/usr/local/lib/node_modules/cfn-lint/src/parser.ts:25:15)
    at Object.validateFile (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:78:27)
    at Command.<anonymous> (/usr/local/lib/node_modules/cfn-lint/src/index.ts:114:32)
    at Command.listener (/usr/local/lib/node_modules/cfn-lint/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/cfn-lint/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/cfn-lint/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/cfn-lint/src/index.ts:183:9)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)```

### PR DESCRIPTION
**Pull request by RazzM13**
Fixes #164.

### CODE REVIEW

**Comment by akdor1154** [comment]
Looks good, and sorry for causing this breakage. I would probably write `Array.isArray(data) ? data : data.split('.')`, but this is getting into realms of personal opinion and it's not my project. :)
